version: "3.8"
services:
  trades-api:
    build: .
    container_name: trades-node-app
    ports:
      - "$PORT:$PORT"
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres:15rc2-alpine
    container_name: db-postgres
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT/tcp"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db-postgres-volume:/var/lib/postgresql/data
      - ./dbcreate.sql:/docker-entrypoint-initdb.d/dbcreate.sql # CREATE TABLES and INSERT Data
volumes:
  db-postgres-volume:
  logs:
